"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useForm } from "react-hook-form";
import { authClient } from "@/lib/auth-client";
import { toast } from "react-toastify";
import { ArrowLeft, BookOpen, Loader2, Plus, Image as ImageIcon, Upload, X, Sparkles } from "lucide-react";
import Link from "next/link";
import type { RoadmapFormData } from "@/lib/types";
import { getAuthToken } from "@/lib/getAuthToken";

const SERVER_URL = process.env.NEXT_PUBLIC_SERVER_URL ?? "http://localhost:8000";

const SUBJECTS = [
  "Web Development", "Machine Learning", "Data Science", "Cloud Computing",
  "Cybersecurity", "Mobile Development", "DevOps", "UI/UX Design",
  "Algorithms & Data Structures", "Databases", "Systems Programming", "Blockchain", "Other",
];

const labelStyle = {
  fontSize: "0.8rem",
  fontWeight: 600 as const,
  color: "rgba(255,255,255,0.6)",
  display: "block" as const,
  marginBottom: "0.4rem",
};

const inputStyle = (hasError: boolean) => ({
  width: "100%",
  padding: "0.7rem 0.9rem",
  borderRadius: "0.6rem",
  background: "rgba(255,255,255,0.05)",
  border: `1px solid ${hasError ? "rgba(239,68,68,0.5)" : "rgba(255,255,255,0.1)"}`,
  color: "white",
  fontSize: "0.9rem",
  outline: "none",
  fontFamily: "inherit",
  transition: "border-color 0.2s",
});

export default function AddRoadmapPage() {
  const router = useRouter();
  const { data: session, isPending } = authClient.useSession();
  const [loading, setLoading] = useState(false);
  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const [uploadingImage, setUploadingImage] = useState(false);

  useEffect(() => {
    if (!isPending && !session) router.push("/auth/signin");
  }, [session, isPending, router]);

  const {
    register,
    handleSubmit,
    formState: { errors },
    watch,
    setValue,
  } = useForm<RoadmapFormData>({
    defaultValues: {
      difficulty: "Beginner",
      isPublic: false,
      estimatedHours: 20,
    },
  });

  const handleImageChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setUploadingImage(true);
    try {
      const formData = new FormData();
      formData.append("file", file);

      const res = await fetch("/api/upload", {
        method: "POST",
        body: formData,
      });
      const result = await res.json();
      if (!result.success) throw new Error(result.error);

      setImageUrl(result.url);
      toast.success("Image uploaded successfully! 📸");
    } catch (err: unknown) {
      const errorMsg = err instanceof Error ? err.message : "Image upload failed";
      toast.error(errorMsg);
    } finally {
      setUploadingImage(false);
    }
  };

  const [generatingDescription, setGeneratingDescription] = useState(false);

  const watchTitle = watch("title");
  const watchSubject = watch("subject");
  const watchDifficulty = watch("difficulty");
  const watchEstimatedHours = watch("estimatedHours");
  const watchShortDescription = watch("shortDescription");

  const handleGenerateDescription = async () => {
    if (!watchTitle || !watchTitle.trim()) {
      toast.error("Please fill in the Roadmap Title first!");
      return;
    }
    if (!watchSubject) {
      toast.error("Please select a Subject first!");
      return;
    }

    setGeneratingDescription(true);
    try {
      const prompt = `Write a detailed learning roadmap description for a roadmap titled "${watchTitle}" in the subject "${watchSubject}" at a "${watchDifficulty || 'Beginner'}" difficulty level. The estimated time to complete is ${watchEstimatedHours || 20} hours. Short summary: "${watchShortDescription || ''}". Focus on detailed learning objectives, prerequisites, and what the student will build. Keep it concise, engaging, under 150 words, and directly output the description text without any conversational preamble or meta-text.`;

      const response = await fetch(`${SERVER_URL}/api/ai/chat`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ message: prompt }),
      });

      const result = await response.json();
      if (!response.ok) {
        throw new Error(result?.message || "AI Service failed");
      }

      const generatedText = result.data?.reply;
      if (generatedText) {
        setValue("description", generatedText.trim(), { shouldValidate: true });
        toast.success("Description generated by AI! 🪄");
      } else {
        throw new Error("No response received from AI");
      }
    } catch (err: unknown) {
      const errorMsg = err instanceof Error ? err.message : "Failed to generate description with AI";
      toast.error(errorMsg);
    } finally {
      setGeneratingDescription(false);
    }
  };

  const onSubmit = async (data: RoadmapFormData) => {
    setLoading(true);
    try {
      const token = await getAuthToken();
      const res = await fetch(`${SERVER_URL}/api/roadmaps`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({
          ...data,
          imageUrl: imageUrl ?? undefined,
        }),
      });
      const result = await res.json();
      if (!result.success) throw new Error(result.error);
      toast.success("Roadmap created successfully! 🚀");
      router.push("/dashboard");
    } catch (err: unknown) {
      const errorMsg = err instanceof Error ? err.message : "Failed to create roadmap";
      toast.error(errorMsg);
    } finally {
      setLoading(false);
    }
  };

  if (isPending) {
    return (
      <div style={{ minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center", color: "#7c3aed" }}>
        <Loader2 size={40} style={{ animation: "spin 1s linear infinite" }} />
        <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
      </div>
    );
  }

  return (
    <div style={{ minHeight: "100vh", padding: "7rem 1.5rem 4rem" }}>
      <style>{`
        @keyframes spin { to { transform: rotate(360deg); } }
        .form-2col { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; }
        .form-desc-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.4rem; gap: 0.75rem; }
        @media (max-width: 520px) {
          .form-2col { grid-template-columns: 1fr !important; }
          .form-desc-header { flex-direction: column; align-items: flex-start; }
          .form-desc-header button { width: 100%; justify-content: center; }
        }
      `}</style>
      <div style={{ maxWidth: "720px", margin: "0 auto" }}>
        <Link href="/dashboard">
          <button style={{ display: "flex", alignItems: "center", gap: "0.4rem", background: "none", border: "none", color: "rgba(255,255,255,0.5)", cursor: "pointer", fontSize: "0.875rem", marginBottom: "2rem" }}>
            <ArrowLeft size={16} /> Back to Dashboard
          </button>
        </Link>

        <div style={{ marginBottom: "2rem" }}>
          <h1 style={{ fontSize: "clamp(1.5rem, 3vw, 2rem)", fontWeight: 900, letterSpacing: "-0.03em", marginBottom: "0.4rem" }}>
            Create a New Roadmap
          </h1>
          <p style={{ color: "rgba(255,255,255,0.45)", fontSize: "0.9rem" }}>
            Define your learning goals and structure your personalised study path.
          </p>
        </div>

        <form onSubmit={handleSubmit(onSubmit)}>
          <div className="glass" style={{ borderRadius: "1.25rem", padding: "2rem", display: "flex", flexDirection: "column", gap: "1.25rem" }}>

            {/* Title */}
            <div>
              <label style={labelStyle}>Roadmap Title *</label>
              <input
                id="input-title"
                placeholder="e.g. Complete React Developer Roadmap"
                {...register("title", { required: "Title is required", minLength: { value: 5, message: "Min 5 characters" } })}
                style={inputStyle(!!errors.title)}
              />
              {errors.title && <p style={{ color: "#f87171", fontSize: "0.75rem", marginTop: "0.3rem" }}>{errors.title.message}</p>}
            </div>

            {/* Subject + Difficulty */}
            <div className="form-2col">
              <div>
                <label style={labelStyle}>Subject *</label>
                <select
                  id="select-subject"
                  {...register("subject", { required: "Subject is required" })}
                  style={{ ...inputStyle(!!errors.subject), cursor: "pointer" }}
                >
                  <option value="" style={{ background: "#0f0f2e" }}>Select subject…</option>
                  {SUBJECTS.map((s) => <option key={s} value={s} style={{ background: "#0f0f2e" }}>{s}</option>)}
                </select>
                {errors.subject && <p style={{ color: "#f87171", fontSize: "0.75rem", marginTop: "0.3rem" }}>{errors.subject.message}</p>}
              </div>

              <div>
                <label style={labelStyle}>Difficulty *</label>
                <select
                  id="select-difficulty"
                  {...register("difficulty")}
                  style={{ ...inputStyle(false), cursor: "pointer" }}
                >
                  {["Beginner", "Intermediate", "Advanced"].map((d) => (
                    <option key={d} value={d} style={{ background: "#0f0f2e" }}>{d}</option>
                  ))}
                </select>
              </div>
            </div>

            {/* Deadline + Estimated Hours */}
            <div className="form-2col">
              <div>
                <label style={labelStyle}>Target Deadline *</label>
                <input
                  id="input-deadline"
                  type="date"
                  {...register("deadline", { required: "Deadline is required" })}
                  style={{ ...inputStyle(!!errors.deadline), colorScheme: "dark" }}
                />
                {errors.deadline && <p style={{ color: "#f87171", fontSize: "0.75rem", marginTop: "0.3rem" }}>{errors.deadline.message}</p>}
              </div>

              <div>
                <label style={labelStyle}>Estimated Hours *</label>
                <input
                  id="input-hours"
                  type="number"
                  min={1}
                  max={10000}
                  {...register("estimatedHours", {
                    required: "Required",
                    min: { value: 1, message: "Min 1 hour" },
                    max: { value: 10000, message: "Max 10,000" },
                  })}
                  style={inputStyle(!!errors.estimatedHours)}
                />
                {errors.estimatedHours && <p style={{ color: "#f87171", fontSize: "0.75rem", marginTop: "0.3rem" }}>{errors.estimatedHours.message}</p>}
              </div>
            </div>

            {/* Short Description */}
            <div>
              <label style={labelStyle}>Short Description *</label>
              <input
                id="input-short-desc"
                placeholder="One-line summary shown on the card (max 150 chars)"
                maxLength={150}
                {...register("shortDescription", { required: "Short description is required" })}
                style={inputStyle(!!errors.shortDescription)}
              />
              {errors.shortDescription && <p style={{ color: "#f87171", fontSize: "0.75rem", marginTop: "0.3rem" }}>{errors.shortDescription.message}</p>}
            </div>

            {/* Full Description */}
            <div>
              <div className="form-desc-header">
                <label style={{ ...labelStyle, marginBottom: 0 }}>Full Description *</label>
                <button
                  id="btn-generate-ai-desc"
                  type="button"
                  onClick={handleGenerateDescription}
                  disabled={generatingDescription}
                  style={{
                    padding: "0.35rem 0.75rem",
                    fontSize: "0.75rem",
                    fontWeight: 600,
                    display: "flex",
                    alignItems: "center",
                    gap: "0.35rem",
                    border: "1px solid rgba(124, 58, 237, 0.35)",
                    color: "#c084fc",
                    background: "rgba(124, 58, 237, 0.12)",
                    borderRadius: "0.5rem",
                    cursor: "pointer",
                    transition: "all 0.2s ease",
                    outline: "none",
                  }}
                  onMouseOver={(e) => {
                    if (!generatingDescription) {
                      e.currentTarget.style.background = "rgba(124, 58, 237, 0.22)";
                      e.currentTarget.style.borderColor = "rgba(124, 58, 237, 0.55)";
                      e.currentTarget.style.transform = "scale(1.03)";
                    }
                  }}
                  onMouseOut={(e) => {
                    e.currentTarget.style.background = "rgba(124, 58, 237, 0.12)";
                    e.currentTarget.style.borderColor = "rgba(124, 58, 237, 0.35)";
                    e.currentTarget.style.transform = "scale(1)";
                  }}
                >
                  {generatingDescription ? (
                    <><Loader2 size={12} style={{ animation: "spin 1s linear infinite" }} /> Generating...</>
                  ) : (
                    <><Sparkles size={12} /> Generate with AI</>
                  )}
                </button>
              </div>
              <textarea
                id="input-description"
                rows={6}
                placeholder="Detailed learning objectives, prerequisites, what you'll build…"
                {...register("description", { required: "Description is required", minLength: { value: 30, message: "Min 30 characters" } })}
                style={{ ...inputStyle(!!errors.description), resize: "vertical", lineHeight: 1.6 }}
              />
              {errors.description && <p style={{ color: "#f87171", fontSize: "0.75rem", marginTop: "0.3rem" }}>{errors.description.message}</p>}
            </div>

            {/* Image Upload */}
            <div>
              <label style={labelStyle}>Roadmap Cover Image</label>
              <div
                style={{
                  border: "1px dashed rgba(255,255,255,0.15)",
                  borderRadius: "0.75rem",
                  padding: "1.5rem",
                  textAlign: "center",
                  background: "rgba(255,255,255,0.02)",
                  display: "flex",
                  flexDirection: "column",
                  alignItems: "center",
                  justifyContent: "center",
                  position: "relative",
                  cursor: "pointer",
                }}
              >
                {uploadingImage ? (
                  <div style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: "0.5rem" }}>
                    <Loader2 size={24} style={{ animation: "spin 1s linear infinite", color: "#7c3aed" }} />
                    <span style={{ fontSize: "0.8rem", color: "rgba(255,255,255,0.6)" }}>Uploading image to Cloudinary...</span>
                  </div>
                ) : imageUrl ? (
                  <div style={{ position: "relative", width: "100%", maxWidth: "300px" }}>
                    <img
                      src={imageUrl}
                      alt="Roadmap Cover"
                      style={{
                        width: "100%",
                        height: "150px",
                        objectFit: "cover",
                        borderRadius: "0.5rem",
                        border: "1px solid rgba(255,255,255,0.1)",
                      }}
                    />
                    <button
                      type="button"
                      onClick={(e) => {
                        e.preventDefault();
                        setImageUrl(null);
                      }}
                      style={{
                        position: "absolute",
                        top: "-8px",
                        right: "-8px",
                        background: "#ef4444",
                        color: "white",
                        border: "none",
                        borderRadius: "50%",
                        width: "24px",
                        height: "24px",
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "center",
                        cursor: "pointer",
                      }}
                    >
                      <X size={14} />
                    </button>
                  </div>
                ) : (
                  <label
                    style={{
                      width: "100%",
                      height: "100%",
                      display: "flex",
                      flexDirection: "column",
                      alignItems: "center",
                      gap: "0.5rem",
                      cursor: "pointer",
                    }}
                  >
                    <Upload size={24} style={{ color: "rgba(255,255,255,0.4)" }} />
                    <span style={{ fontSize: "0.85rem", color: "rgba(255,255,255,0.6)" }}>
                      Click or drag an image here to upload
                    </span>
                    <span style={{ fontSize: "0.75rem", color: "rgba(255,255,255,0.4)" }}>
                      PNG, JPG, JPEG up to 5MB
                    </span>
                    <input
                      type="file"
                      accept="image/*"
                      onChange={handleImageChange}
                      style={{ display: "none" }}
                    />
                  </label>
                )}
              </div>
            </div>

            {/* Public toggle */}
            <div
              style={{
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
                background: "rgba(255,255,255,0.03)",
                border: "1px solid rgba(255,255,255,0.08)",
                borderRadius: "0.75rem",
                padding: "1rem 1.25rem",
              }}
            >
              <div>
                <p style={{ fontWeight: 600, fontSize: "0.9rem", marginBottom: "0.2rem" }}>Make Public</p>
                <p style={{ color: "rgba(255,255,255,0.4)", fontSize: "0.8rem" }}>
                  Share this roadmap with the community on the Explore page.
                </p>
              </div>
              <label style={{ position: "relative", display: "inline-block", width: "48px", height: "26px", flexShrink: 0 }}>
                <input
                  id="toggle-public"
                  type="checkbox"
                  {...register("isPublic")}
                  style={{ position: "absolute", opacity: 0, width: 0, height: 0, pointerEvents: "none" }}
                />
                <span
                  style={{
                    position: "absolute",
                    top: 0,
                    right: 0,
                    bottom: 0,
                    left: 0,
                    background: watch("isPublic") ? "linear-gradient(135deg, #7c3aed, #4f46e5)" : "rgba(255,255,255,0.1)",
                    borderRadius: "26px",
                    cursor: "pointer",
                    transition: "background 0.3s",
                    border: "1px solid rgba(255,255,255,0.15)",
                    overflow: "hidden",
                  }}
                >
                  <span
                    style={{
                      position: "absolute",
                      left: watch("isPublic") ? "24px" : "2px",
                      top: "2px",
                      width: "20px",
                      height: "20px",
                      borderRadius: "50%",
                      background: "white",
                      transition: "left 0.3s",
                      boxShadow: "0 1px 4px rgba(0,0,0,0.3)",
                    }}
                  />
                </span>
              </label>
            </div>

            <button
              id="btn-create-roadmap"
              type="submit"
              disabled={loading}
              className="btn-primary"
              style={{ width: "100%", marginTop: "0.5rem" }}
            >
              <span style={{ display: "flex", alignItems: "center", justifyContent: "center", gap: "0.5rem", flexWrap: "nowrap", whiteSpace: "nowrap" }}>
                {loading ? (
                  <><Loader2 size={16} style={{ animation: "spin 1s linear infinite" }} /> Creating…</>
                ) : (
                  <><Plus size={16} /> Create Roadmap</>
                )}
              </span>
            </button>
          </div>
        </form>
      </div>

      <style>{``}</style>
    </div>
  );
}
